cnn:
  description: "ConvNet for multi category classification"
  image_dim: 425
  n_channels: 3
  n_classes: 80
  hyperparams:
    channel_sizes: [8, 12, 16]
    kernel_sizes: [4, 7, 9]
    layer_sizes: [4096, 128, 80]

vae:
  description: "Variational autoencoder for image compression and classification from latent space"
  image_dim: 425
  n_channels: 3
  n_classes: 80
  hyperparams:
    channel_sizes: [8, 12, 16]
    kernel_sizes: [4, 7, 9]
    layer_sizes: [4096, 128, 80]

gnn:
  description: "Graph neural network for fmri decoding"
  image_dim: 425
  n_channels: 3
  n_classes: 80
  hyperparams:
    channel_sizes: [8, 12, 16]
    kernel_sizes: [4, 7, 9]
    layer_sizes: [4096, 128, 80]

gru:
  description: "GRU for fmri decoding"
  image_dim: 425
  n_channels: 3
  n_classes: 80
  hyperparams:
    channel_sizes: [8, 12, 16]
    kernel_sizes: [4, 7, 9]
    layer_sizes: [4096, 128, 80]