alpha: 0.9  # how much to weigh the fmri loss. 1.0 means cat loss is ignored
beta: 0.5   # how much to weigh the left hemisphere. 1.0 means right hemisphere is ignored
alex_size: 100
lh_size: 19004
rh_size: 20544
cat_size: 80
lr: 0.001
batch_size: 32
n_steps: 6000
k_folds: 5
latent_dim: 100
n_layers:
  img: 2
  fmri: 1
  cat: 1
n_units:
  img: 100
  fmri: 100
  cat: 100