data:
  large_image_size: 425
  small_image_size: 85
  n_channels: 3
  n_classes: 80

model:
  description: "ConvNet for multi category classification"
  hyperparams:
    small:
      channel_sizes: [8, 12, 16]
      kernel_sizes: [4, 7, 9]
      layer_sizes: [256, 128, 80]
    large:
      channel_sizes: [8, 12, 16]
      kernel_sizes: [4, 7, 9]
      layer_sizes: [4096, 128, 80]