alpha: 0.99  # how much to weigh the fmri loss. 1.0 means cat loss is ignored
beta: 1.0   # how much to weigh the left hemisphere. 1.0 means right hemisphere is ignored
dropout: 0.4
alex_size: 100
weight_decay: 0.001
lh_size: 19004
rh_size: 20544
cat_size: 80
lr: 0.001
batch_size: 32
n_steps: 6000
k_folds: 5
latent_dim: 100
n_layers:
  img: 2
  fmri: 2
  cat: 2
n_units:
  img: 100
  fmri: 100
  cat: 100