subjects:
  subj01:
    lh_fmri_size: 19004
    rh_fmri_size: 20544
  subj02:
    lh_fmri_size: 19004
    rh_fmri_size: 20544
  subj03:
    lh_fmri_size: 19004
    rh_fmri_size: 20544
  subj04:
    lh_fmri_size: 19004
    rh_fmri_size: 20544
  subj05:
    lh_fmri_size: 19004
    rh_fmri_size: 20544
  subj06: 
    lh_fmri_size: 18978
    rh_fmri_size: 20220
  subj07: 
    lh_fmri_size: 19004
    rh_fmri_size: 20544
  subj08: 
    lh_fmri_size: 18981
    rh_fmri_size: 20530