subj05:
  left_hem:
    EBA: 3618
    FBA-1: 512
    FBA-2: 984
    FFA-1: 542
    FFA-2: 335
    OFA: 778
    OPA: 2203
    OWFA: 579
    PPA: 1585
    RSC: 358
    V1d: 1117
    V1v: 538
    V2d: 663
    V2v: 531
    V3d: 725
    V3v: 457
    VWFA-1: 654
    VWFA-2: 329
    aTL-faces: 0
    early: 5169
    hV4: 584
    lateral: 3136
    mTL-bodies: 0
    mTL-faces: 0
    mTL-words: 0
    mfs-words: 257
    midlateral: 1098
    midparietal: 854
    midventral: 863
    parietal: 2336
    ventral: 4972
  right_hem:
    EBA: 5741
    FBA-1: 556
    FBA-2: 200
    FFA-1: 658
    FFA-2: 650
    OFA: 883
    OPA: 2025
    OWFA: 412
    PPA: 1586
    RSC: 726
    V1d: 706
    V1v: 589
    V2d: 796
    V2v: 629
    V3d: 714
    V3v: 487
    VWFA-1: 313
    VWFA-2: 338
    aTL-faces: 0
    early: 5302
    hV4: 336
    lateral: 3574
    mTL-bodies: 0
    mTL-faces: 0
    mTL-words: 0
    mfs-words: 340
    midlateral: 1188
    midparietal: 1138
    midventral: 1050
    parietal: 2318
    ventral: 4852
