method: bayes
name: sweep
metric:
  name: val_rh_corr
  goal: maximize
parameters:
  beta:
    distribution: uniform
    min: 0.0
    max: 1.0
  alpha:
    distribution: uniform
    min: 0.0
    max: 1.0
  batch_size:
    value: 32
  n_units:
    value: 100
  n_layers:
    value: 2
  dropout:
    value: 0.20
  n_steps:
    value: 4000
  latent_dim:
    value: 100
  k_folds:
    value: 5

