method: bayes
metric:
  name: val_rh_corr
  goal: maximize
parameters:
  learning_rate:
    distribution: exponential
    min: 0.0001
    max: 0.1
  beta:
    distribution: uniform
    min: 0.0
    max: 1.0
  alpha:
    distribution: uniform
    min: 0.0
    max: 1.0
  batch_size:
    values: [16, 32, 64, 128]
  num_units:
    values: [100, 200, 300, 400, 500]
  dropout:
    values: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6]
  weight_decay:
    values: [0.0, 0.0001, 0.001, 0.01, 0.1]
  n_steps:
    values: [1000, 2000, 3000, 4000, 5000, 6000]
  latent_dim:
    values: [50, 100, 150, 200, 250]

