name: TODO to Issue

on:
  push:
    branches: [ main ]

jobs:
  todo-to-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: TODO to Issue
        uses: peter-evans/todo-to-issue@v1.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
