name: TODO to Issue
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Convert TODOs to Issues
        uses: alstr/todo-to-issue-action@v4
        with:
          auto_assign: true
          identifiers: |
            - TODO
            - FIXME
